import {
    LayoutDashboard,
    Users,
    UsersRound,
    Building2,
    ClipboardList,
    CalendarClock,
    XSquare,
    CalendarDays,
    FileText,
    Wallet,
    UserSearch,
    Target,
    Boxes,
    Settings,
    ListChecks,
    FileStack,
    UserCog,
    Banknote,
    Clock,
    Receipt,
    BarChart3,
    Settings2,
    ShieldCheck,
    MonitorSmartphone,
    ScanFace,
    Clock9,
    Layers,
    Laptop,
    Network,
    FolderOpen,
    type LucideIcon,
} from 'lucide-react';

// Icon lookup shared by TopNav (module tabs) and ContextSidebar (module
// children) — keyed by the string names used in config/menuConfig.ts so the
// config stays serializable (mirrors how the DB-backed menu_items table
// stores icon names as strings too).
export const NAV_ICONS: Record<string, LucideIcon> = {
    LayoutDashboard,
    Users,
    UsersRound,
    Building2,
    ClipboardList,
    CalendarClock,
    XSquare,
    CalendarDays,
    FileText,
    Wallet,
    UserSearch,
    Target,
    Boxes,
    Settings,
    ListChecks,
    FileStack,
    UserCog,
    Banknote,
    Clock,
    Receipt,
    BarChart3,
    Settings2,
    ShieldCheck,
    MonitorSmartphone,
    ScanFace,
    Clock9,
    Layers,
    Laptop,
    Network,
    FolderOpen,
};
